const areaData=[
    {
        value:1,
        label:'云南',
        children:[
            {
                value:871,
                label:'昆明',
                children:[
                    {
                        value:871001,
                        label:'五华区',
                        children:[]
                    },{
                        value:871002,
                        label:'盘龙区',
                        children:[]
                    }
                ]
            },{
                value:872,
                label:'玉溪',
                children:[
                    {
                        value:872001,
                        label:'红塔区',
                        children:[]
                    },{
                        value:872002,
                        label:'函数式',
                        children:[]
                    }
                ]
            }
        ]
    }
]
export default areaData
